### ISSUE TITLE
Handle server failure

### ISSUE THREAD

**Issue by webfrea-k** [rsocket/rsocket-kotlin#145]
I have a multiplatform (iOS and Android) app, which gets the data from our own rsocket server. We are connecting to the server like this: 
```
val transport = aSocket(SelectorManager()).tcp().clientTransport(hostname = host, port = 8000)
api.connector(uniqueDeviceId).connect(transport)
```
## Expected Behavior
We want to catch connection failures and handle them with our own logic (reconnect, end, ...).

## Actual Behavior
When server goes down (forcibly), the multiplatform apps crash (Android with ClosedReceiveChannelException, iOS just freezes and no longer responds to clicks etc.). 

## Question
What is the correct way to catch connection errors in `commonMain`? We have implemented the `reconnectable` like below, but this only works if the server is down when the app starts. If server fails when the connection is already established, the app crashes on both platforms (something similar happens if WiFi is turned off while the app is running).

```
internal fun connector(uniqueDeviceId: String): RSocketConnector = RSocketConnector {
        reconnectable(3) {
            warningLog("Unable to connect to server")
            delay(1000)
            true
        }

        connectionConfig {
            payloadMimeType = PayloadMimeType(
                metadata = WellKnownMimeType.MessageRSocketCompositeMetadata.text
            )
            setupPayload {
                buildPayload {
                    data(uniqueDeviceId)
                    compositeMetadata {
                        add(RoutingMetadata("initial"))
                    }
                }
            }
        }
    }
```
We have tried to follow this pattern: https://github.com/rsocket/rsocket-kotlin/blob/master/examples/interactions/src/jvmMain/kotlin/ReconnectExample.kt#L82 but the app crashes (ClosedReceiveChannelException) like before. Any help or redirect to the correct channel will be much appreciated.

## Environment
kotlinVersion=1.4.31
coroutinesBaseVersion=1.4.2
ktorVersion=1.5.2
rsocketVersion=0.12.0
serializationVersion=1.1.0
klockVersion=2.0.6
googleServicesVersion=4.3.3
buildKonfigVersion=0.7.0
atomicFuVersion=0.14.4
korlibsKrypto=2.0.2
gradleAndroidVersion=4.1.3
dokkaVersion=1.4.20
mockkVersion=1.10.3-jdk8
firebaseMessagingVersion=21.0.1

**Comment by whyoleg** [comment]
Hey, reproduced on my side issue with reconnect. Investigating. At my side it works on JVM with TCP all time BTW.
`ClosedReceiveChannelException` is produced by transport specifics - both in TCP and WS implementations. Looks like it will be better to provide some custom exception for case of failed connection, will look into it.

**Comment by webfrea-k** [comment]
Hey, thanks for getting back to me. In the meanwhile, I've been busy trying to figure it out as well. Here are my findings:
I have created my own `TcpConnection` class and it seems that the error is thrown somewhere in `openWriteChannel().use` and `openReadChannel().apply`. I've wrapped both in try-catch and it seems to fix the issue on android (connection gets re-established if server gets back online in `reconnectable` time:
```
launch {
            socket.openWriteChannel(autoFlush = true).use {
                while (isActive) {
                    try {
                        val packet = sendChannel.receive()
                        val length = packet.remaining.toInt()
                        writePacket {
                            writeLength(length)
                            writePacket(packet)
                        }
                    } catch (t: Throwable) {
                        errorLog(t.printStackTrace())
                        job.completeExceptionally(Throwable("Error"))
                    }
                }
            }
        }
        
        launch {
            socket.openReadChannel().apply {
                while (isActive) {
                    try {
                        val length = readPacket(3).readLength()
                        val packet = readPacket(length)
                        receiveChannel.send(packet)
                    } catch (t: Throwable) {
                        errorLog(t.printStackTrace())
                        socket.close()
                        job.completeExceptionally(Throwable("Error"))
                    }
                }
            }
        }
```

Sadly this try-catch does not fix the issue on iOS. CPU on simulator immediately reaches 100% utilization and the screen becomes unresponsive. I haven't been able to fix this so far, but as it seems some coroutine job gets stuck somewhere in `ReadByteChannelNative`. Any pointers for a workaround on iOS side?

Thanks :)

**Comment by webfrea-k** [comment]
I have prepared a reproducer repo based on your playground module: https://github.com/webfrea-k/rsocket-kotlin/tree/ios-error-reproducer

**Reproducing steps:**
1. Turn on `TCPServerAppKt`
2. Open and run ios app (root/iosApp)
3. Click "Start request stream" on emulator
4. Turn off `TCPServerAppKt`

App UI will freeze and CPU will stay at 100%. Nothing can be done until the app is killed.
If you do the same with `TcpClienApp.kt` in `jvmMain` it will print:
```
[1, 1, 1]
[]
[]
[]
Error was thrown, caught & ignored

Process finished with exit code 0
```
Let me know if anything else is needed.

**Comment by whyoleg** [comment]
Hey, thx for reproducer, I've already reproduced it just using `macos` target. Still investigating, haven't found the root cause of the issue. It can be both because of some `ktor` internal issue, and because of some bad usage of kotlin MM with coroutines (dispatcher switching). Will post more info when I will find something.

**Comment by whyoleg** [comment]
Finally found the root cause of the issue, and looks like it's `ktor` issue, will create issue + minimal reproducer and will post it here soon.

### The issue, and what we can do now

Here I will describe what I've found for K/N TCP client, K/JVM can also be affected, will check it later.

#### Issue

`ByteReadChannel.readPacket` don't check if channel is closed during it suspension, and so, after connection is closed, channel is closed, and channel will freeze forever on this call, even after canceling it, or scope/job in which it works - it will have no effect, because looks like it freezes somewhere in blocking context internally.

#### What we can do now

I've found workaround for this, for some reason, `ByteReadChannel.readRemaining` checks, that the channel is closed during it suspension, but it can return not full buffer - we can check it and handle. 
BUT! 
Looks like there is one more issue here, as this call somehow affects writing to socket, because just after connection, SETUP frame is sent, but after that, no frames possible to write (send to socket), until it receives another frame (f.e. keep alive frame), and so, this way it will also not work as a workaround. This can be both because of the some internal K/N ktor issues, and also because of some thread-safety and so locks inside implementation.

All in all, current implementation will freeze after server failure, implementation with `readRemaining` will lag all time.

I will continue with investigation, and will try to find workaround, that will work until something in `ktor` will be fixed (or may be `ktor` developers will have workaround).

_Note: checked and reproduced on current master branch. Will check soon on branch with ktor 1.5.3, may be there were some changes related_

**Comment by whyoleg** [comment]
Looks like fixed in https://github.com/rsocket/rsocket-kotlin/pull/149
Will add tests later...

**Comment by webfrea-k** [comment]
Thanks for the quick resolution @whyoleg. I've tried your workaround and I can confirm it works as expected on iOS now.
Keep up the good work with this library! :)

Closing issue.
